# -*- coding: utf-8 -*-
"""AI Text Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duryfzk4S1wblZk0h3lbo3fk0L6Z4qX4
"""

from transformers import pipeline
generator = pipeline('text-generation', model='gpt2')
prompt="Artificial Intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text")
print(result[0]['generated_text'])

