# -*- coding: utf-8 -*-
"""product review analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GXXt-JZf6924l53HXXkU6jXWrOIpgObH
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

sentiment = pipeline("sentiment-analysis")
reviews = """"The laptop starts quickly and works smoothly for daily starts.
The screen quality is clear amd good for watching videos.
Battery backup it average and needs charging often.
The fan makes noise when many apps are renning.
Overall, it is a good laptop for everyday use."""
sentences = reviews.split(".")
pros = []
cons = []
for s in sentences:
  s = s.strip()
  if s=="":
    continue
  result = sentiment(s)[0]

  if result["label"] == "POSITIVE":
      pros.append(s)
  elif result["label"] == "NEGATIVE":
      cons.append(s)
pros = pros[:2]
cons = cons[:2]
df = pd.DataFrame({
    "pros": pros,
    "cons": cons
})
df

