# -*- coding: utf-8 -*-
"""sentence similarites

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f_C3B0y_zJLMIiD9lE_EuLIVEjuHdywJ
"""

!pip install transformers torch

from transformers import pipeline
generator = pipeline(
    "text-generation",
    model = "gpt2"
)
prompt = "Artificial Intelligence in finance will"
result = generator(prompt, max_length=50, num_return_sequences=1)
print("Ai Generated Text:")
print(result[0]['generated_text'])

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)
similarity = util.cos_sim(embedding1, embedding2)
print("/nSimilarity Score:", round(float(similarity),2))
if similarity > 0.75:
  print("SimilarityLevel:High")
elif similarity > 0.4:
    print("Similarity Level: Medium")
else:
    print("Similarity Level: Low")