# -*- coding: utf-8 -*-
"""TIMETABLE GENERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfKT4o6ID2GnHAIiBuZecqhDXS8Mddn8
"""

import pandas as pd
import random
print("TMETABLE GENERATOR\n")
subjects_input = input("Enter the subjects (comma separated): ")
days_input = input("Enter the days (comma separated): ")
periods_per_day = int(input("Enter the number of periods per day: "))
subjects = [s.strip() for s in subjects_input.split(',') if s.strip()]
days = [d.strip() for d in days_input.split(',') if d.strip()]
if len(subjects) == 0 or len(days) == 0 or periods_per_day <=0:
  print("Invalid input. Please try again.")
else:
    timetable = {}
    for day in days:
        timetable[day] = random.choices(subjects, k=period_per_day)
    df = pd.DataFrame(timetable)
    df.index = [f"period {i+1}" for i in range(periods_per_day)]
    print("/nTimetable Generated Successfully\n")
    display(df)
    df.to_csv("timetable.csv")
    print("\nTimetable saved as timetable.csv")

